git:
  depth: 99999

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    update: true
  chrome: stable

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr /home/travis/.m2/repository/webdriver/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome
  - rm -fr /home/travis/.m2/repository/webdriver/
  - mkdir -p /home/travis/.gradle
  - openssl aes-256-cbc -K ${encrypted_5bc7821a2315_key} -iv ${encrypted_5bc7821a2315_iv} -in config/secring.gpg.enc -out /home/travis/.gradle/secring.gpg -d

install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - ./gradlew check --no-daemon --console=plain
  - ./gradlew htmlunit --no-daemon --console=plain
  - ./gradlew chrome --no-daemon --console=plain
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./gradlew sonarqube -x test --no-daemon --console=plain -Dsonar.organization=${SONAR_ORG} -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_LOGIN} -Dsonar.branch.name=${TRAVIS_BRANCH}; fi
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then ./gradlew uploadArchives --no-daemon --console=plain -Psigning.keyId=${SIGNING_KEY_ID} -Psigning.password=${SIGNING_PASSWORD} -Psigning.secretKeyRingFile=/home/travis/.gradle/secring.gpg; -PsonatypeUsername=${sonatypeUsername} -PsonatypePassword=${sonatypePassword} fi

after_script:
  - rm -fr /home/travis/.gradle/secring.gpg
  - ./.upload_reports.sh

notifications:
  slack:
    rooms:
      secure: "a+W3yrcab0GVRhmIUXsdV1KpNxX6Qe7LnX6vq4Ou4mCSSaBln0mL0y4Gs1GSPdiq5PWhYrcIgAsESQiCDbi5JoW//GyEovZvY+WDgnhrskoOLFgWqxhT1yInDkLRfkQZAdL/5uWOBDSr1d+2/1qqeciWMebQQZoEezeKoKwPtdQ="
