branches:
  only:
    - master

notifications:
  slack:
    rooms:
      secure: "a+W3yrcab0GVRhmIUXsdV1KpNxX6Qe7LnX6vq4Ou4mCSSaBln0mL0y4Gs1GSPdiq5PWhYrcIgAsESQiCDbi5JoW//GyEovZvY+WDgnhrskoOLFgWqxhT1yInDkLRfkQZAdL/5uWOBDSr1d+2/1qqeciWMebQQZoEezeKoKwPtdQ="

language: java
sudo: true
cache:
  directories:
  - $HOME/.gradle

script:
    - ./gradlew clean check
    - ./gradlew test
    #- ./gradlew chrome
    #- ./gradlew htmlunit
    - ./gradlew uploadArchives --info
      -Psigning.keyId=System.getenv('signing.keyId')
      -Psigning.password=System.getenv('signing.password')"
      -Psigning.secretKeyRingFile=~\/.gradle/secring.gpg

jdk:
- oraclejdk8
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - rm -fr /home/travis/.m2/repository/webdriver/
 - openssl aes-256-cbc -K $encrypted_5bc7821a2315_key -iv $encrypted_5bc7821a2315_iv -in config/secring.gpg.enc -out ~\/.gradle/secring.gpg -d

after_success:
- ./gradlew jacocoTestReport coveralls
- bash <(curl -s https://codecov.io/bash)

after_script: "./.upload_reports.sh"
