name: 'Upload apps to Browserstack. They delete an uploaded app after 30 days from the day of upload'
on:
  workflow_dispatch:
  schedule:
    - cron: '40 7 27 * *'

jobs:
  upload-apps-to-browserstack:
    env:
      BS_KEY: ${{ secrets.BS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run script
        run: |
          ./.github/upload_test_apps.sh
        shell: bash
